version: 2.1
orbs:
  node: circleci/node@7.0.0
  slack: circleci/slack@5.1.1

jobs:
  build:
    docker:
      - image: cimg/node:lts
    resource_class: arm.medium
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
          override-ci-command: yarn install --immutable
      - run:
          name: Build testing site
          command: yarn build
      - slack/notify:
          event: fail
          template: basic_fail_1
          channel: ntf-topmonks-webs
  test:
    docker:
      - image: cimg/node:lts
    resource_class: arm.medium
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
          override-ci-command: yarn install --immutable
      - run: yarn test
      - slack/notify:
          event: fail
          template: basic_fail_1
          channel: ntf-topmonks-webs
workflows:
  ci:
    jobs:
      - build:
          context: org-global
      - test:
          context: org-global
